name: The Tales of B Continued
baseurl: /bbaillie2.github.io
description: A continuation of The Tales of B by Bronwyn Baillie

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
