name: The Tales of B Continued
url: https://bbaillie2.github.io
description: A continuation of The Tales of B

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
